### PR TITLE
feat(package.json): added typescript packages to support TS

### PR DESCRIPTION
**Pull request by pablohpsilva**
Added external dependencies so `mhy` could work on typescript projects

### CODE REVIEW

**Comment by wintercounter** [comment]
Types will most probably need to be added at a later point, but until it's YAGNI.

**Comment by wintercounter** [comment]
@all-contributors please add FabianLauer for code

**Comment by wintercounter** [comment]
@all-contributors please add thomaswinckell for code, doc

**Comment by wintercounter** [comment]
@all-contributors please add stevenmitts for doc

**Comment by FabianLauer** [comment]
@wintercounter bit late but thanks for adding me 😄

**Comment by wintercounter** [comment]
I tried to add everyone and simply used this old PR to comment for the robot :)

**Comment by FabianLauer** [comment]
@wintercounter by "bit late" i meant bit late for me to reply here, not "bit late" for adding me as contributor. I really didn't contribute all to much here yet 😉

**Pull request closed without merging**
